# Generated by Django 6.0.2 on 2026-03-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_invoice_period_end_invoice_period_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
