# Generated by Django 6.0.2 on 2026-03-26 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_invoice_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("username", models.CharField(max_length=150)),
                ("password_hash", models.CharField(max_length=255)),
                ("plan_id", models.CharField(max_length=50)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
