# Generated by Django 6.0.2 on 2026-03-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_onboardingsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_method_details",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
