# Generated by Django 6.0.2 on 2026-03-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0003_backfill_company_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consolidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ship_type",
                    models.CharField(
                        choices=[("AIR", "Air"), ("SEA", "Sea"), ("GROUND", "Ground")],
                        max_length=10,
                    ),
                ),
                (
                    "consolidation_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("alt_name", models.CharField(blank=True, max_length=255, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True, editable=False, max_length=20, unique=True
                    ),
                ),
                (
                    "associate_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidations",
                        to="company.associatecompany",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidations",
                        to="company.company",
                    ),
                ),
                (
                    "receiving_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiving_consolidations",
                        to="company.office",
                    ),
                ),
                (
                    "sending_office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sending_consolidations",
                        to="company.office",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="consolidati_company_f29053_idx",
                    ),
                    models.Index(
                        fields=["company", "ship_type"],
                        name="consolidati_company_71f920_idx",
                    ),
                ],
            },
        ),
    ]
