# Generated by Django 6.0.2 on 2026-03-07 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_backfill_company_data"),
        ("consolidation", "0001_initial"),
        ("receiving", "0005_add_receipt_fields_and_receipt_line"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsolidationReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidation_receipts",
                        to="company.company",
                    ),
                ),
                (
                    "consolidation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_links",
                        to="consolidation.consolidation",
                    ),
                ),
                (
                    "warehouse_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consolidation_links",
                        to="receiving.warehousereceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consolidation", "warehouse_receipt"),
                        name="unique_consolidation_receipt",
                    )
                ],
            },
        ),
    ]
