# Generated by Django 6.0.2 on 2026-03-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_backfill_company_data"),
        ("warehouse", "0002_storagelocation_company_warehouse_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storagelocation",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="storage_locations",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouses",
                to="company.company",
            ),
        ),
    ]
