# Generated by Django 5.2

from django.db import migrations

def backfill_company_data(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    
    # Create or get Default Company
    default_company, created = Company.objects.get_or_create(name="Default Company")
    
    # 1. Backfill core entities
    Client = apps.get_model('clients', 'Client')
    Client.objects.filter(company__isnull=True).update(company=default_company)
    
    Warehouse = apps.get_model('warehouse', 'Warehouse')
    Warehouse.objects.filter(company__isnull=True).update(company=default_company)
    
    # 2. Backfill child entities from parents if possible, else default
    StorageLocation = apps.get_model('warehouse', 'StorageLocation')
    for loc in StorageLocation.objects.filter(company__isnull=True).iterator():
        loc.company = loc.warehouse.company if loc.warehouse and loc.warehouse.company else default_company
        loc.save(update_fields=['company'])
        
    WarehouseReceipt = apps.get_model('receiving', 'WarehouseReceipt')
    for wr in WarehouseReceipt.objects.filter(company__isnull=True).iterator():
        wr.company = wr.client.company if wr.client and wr.client.company else default_company
        wr.save(update_fields=['company'])
        
    RepackOperation = apps.get_model('receiving', 'RepackOperation')
    for ro in RepackOperation.objects.filter(company__isnull=True).iterator():
        ro.company = ro.client.company if ro.client and ro.client.company else default_company
        ro.save(update_fields=['company'])
        
    RepackLink = apps.get_model('receiving', 'RepackLink')
    for rl in RepackLink.objects.filter(company__isnull=True).iterator():
        rl.company = rl.repack_operation.company if rl.repack_operation and rl.repack_operation.company else default_company
        rl.save(update_fields=['company'])
        
    Shipment = apps.get_model('shipping', 'Shipment')
    for ship in Shipment.objects.filter(company__isnull=True).iterator():
        ship.company = ship.client.company if ship.client and ship.client.company else default_company
        ship.save(update_fields=['company'])
        
    ShipmentItem = apps.get_model('shipping', 'ShipmentItem')
    for item in ShipmentItem.objects.filter(company__isnull=True).iterator():
        item.company = item.shipment.company if item.shipment and item.shipment.company else default_company
        item.save(update_fields=['company'])
        
    # 3. Backfill inventory tracking
    InventoryBalance = apps.get_model('inventory', 'InventoryBalance')
    for ib in InventoryBalance.objects.filter(company__isnull=True).iterator():
        ib.company = ib.client.company if ib.client and ib.client.company else default_company
        ib.save(update_fields=['company'])
        
    InventoryTransaction = apps.get_model('inventory', 'InventoryTransaction')
    for it in InventoryTransaction.objects.filter(company__isnull=True).iterator():
        it.company = it.client.company if it.client and it.client.company else default_company
        it.save(update_fields=['company'])
        
    InventoryTransactionLine = apps.get_model('inventory', 'InventoryTransactionLine')
    for itl in InventoryTransactionLine.objects.filter(company__isnull=True).iterator():
        itl.company = itl.transaction.company if itl.transaction and itl.transaction.company else default_company
        itl.save(update_fields=['company'])

def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_associatecompany_office'),
        ('clients', '0002_client_company'),
        ('warehouse', '0002_storagelocation_company_warehouse_company'),
        ('receiving', '0003_repacklink_company_repackoperation_company_and_more'),
        ('shipping', '0002_shipment_company_shipmentitem_company'),
        ('inventory', '0002_inventorybalance_company_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_company_data, reverse_backfill),
    ]
