# Generated by Django 6.0.2 on 2026-03-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0004_company_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="subscription_cancel_at_period_end",
            field=models.BooleanField(default=False),
        ),
    ]
