# Generated by Django 6.0.2 on 2026-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0005_company_subscription_cancel_at_period_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="subscription_queued_plan",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
