# Generated by Django 6.0.2 on 2026-02-20 22:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WarehouseReceipt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "wr_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("carrier", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SHIPPED", "Shipped"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "weight_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("LB", "Pounds"), ("KG", "Kilograms")],
                        default="LB",
                        max_length=5,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dimension_unit",
                    models.CharField(
                        choices=[("IN", "Inches"), ("CM", "Centimeters")],
                        default="IN",
                        max_length=5,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouse_receipts",
                        to="clients.client",
                    ),
                ),
                (
                    "parent_wr",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_wrs",
                        to="receiving.warehousereceipt",
                    ),
                ),
                (
                    "received_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.warehouse",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="receiving_w_status_4499db_idx"
                    ),
                    models.Index(
                        fields=["received_at"], name="receiving_w_receive_ec6af6_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("tracking_number__isnull", False)),
                        fields=("client", "tracking_number"),
                        name="unique_client_tracking_number",
                    )
                ],
            },
        ),
    ]
