# Generated by Django 6.0.2 on 2026-02-20 22:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
        ("receiving", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepackOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("CONSOLIDATE", "Consolidate"), ("REPACK", "Repack")],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repack_operations",
                        to="clients.client",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repack_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepackLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_wr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repack_as_input",
                        to="receiving.warehousereceipt",
                    ),
                ),
                (
                    "output_wr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repack_as_output",
                        to="receiving.warehousereceipt",
                    ),
                ),
                (
                    "repack_operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="receiving.repackoperation",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="repackoperation",
            index=models.Index(
                fields=["performed_at"], name="receiving_r_perform_5af894_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repacklink",
            index=models.Index(
                fields=["repack_operation"], name="receiving_r_repack__6358e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repacklink",
            index=models.Index(
                fields=["input_wr"], name="receiving_r_input_w_0a8002_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repacklink",
            index=models.Index(
                fields=["output_wr"], name="receiving_r_output__42ea4f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="repacklink",
            constraint=models.UniqueConstraint(
                fields=("repack_operation", "input_wr"), name="uniq_repackop_inputwr"
            ),
        ),
        migrations.AddConstraint(
            model_name="repacklink",
            constraint=models.CheckConstraint(
                condition=models.Q(("input_wr", models.F("output_wr")), _negated=True),
                name="check_input_not_equal_output",
            ),
        ),
    ]
