# Generated by Django 6.0.2 on 2026-03-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_associatecompany_office"),
        ("receiving", "0002_repackoperation_repacklink_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repacklink",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repack_links",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="repackoperation",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repack_operations",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="warehousereceipt",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_receipts",
                to="company.company",
            ),
        ),
    ]
