# Generated by Django 6.0.2 on 2026-03-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_backfill_company_data"),
        ("receiving", "0003_repacklink_company_repackoperation_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repacklink",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repack_links",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="repackoperation",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="repack_operations",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="warehousereceipt",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_receipts",
                to="company.company",
            ),
        ),
    ]
