# Generated by Django 6.0.2 on 2026-03-06 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_backfill_company_data"),
        ("receiving", "0004_alter_repacklink_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehousereceipt",
            name="allow_repacking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="warehousereceipt",
            name="associate_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warehouse_receipts",
                to="company.associatecompany",
            ),
        ),
        migrations.AddField(
            model_name="warehousereceipt",
            name="location_note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="warehousereceipt",
            name="receipt_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="warehousereceipt",
            name="recipient_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="warehousereceipt",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="warehousereceipt",
            name="shipping_method",
            field=models.CharField(
                blank=True,
                choices=[("air", "Air"), ("sea", "Sea"), ("ground", "Ground")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="WarehouseReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("carrier", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "package_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "declared_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("pieces", models.PositiveIntegerField(default=1)),
                (
                    "volume_cf",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("repackable", models.BooleanField(default=False)),
                ("bill_invoice", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="company.company",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="receiving.warehousereceipt",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["receipt"], name="receiving_w_receipt_7e05b5_idx"
                    ),
                    models.Index(
                        fields=["company"], name="receiving_w_company_377dcd_idx"
                    ),
                ],
            },
        ),
    ]
