# Generated by Django 6.0.2 on 2026-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0005_add_receipt_fields_and_receipt_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousereceipt',
            name='wr_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='warehousereceiptline',
            name='volume_cf',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
