# Generated by Django 6.0.2 on 2026-04-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiving', '0007_warehousereceiptlinetracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousereceipt',
            name='is_repack',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
