# Generated by Django 6.0.2 on 2026-02-20 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("receiving", "0002_repackoperation_repacklink_and_more"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("PACKED", "Packed"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("destination_name", models.CharField(blank=True, max_length=255)),
                (
                    "destination_address_line1",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "destination_address_line2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("destination_city", models.CharField(blank=True, max_length=100)),
                ("destination_state", models.CharField(blank=True, max_length=100)),
                ("destination_zip", models.CharField(blank=True, max_length=20)),
                ("carrier", models.CharField(blank=True, max_length=100)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="clients.client",
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="warehouse.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shipping.shipment",
                    ),
                ),
                (
                    "wr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_items",
                        to="receiving.warehousereceipt",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["client"], name="shipping_sh_client__8325e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["status"], name="shipping_sh_status_0644c6_idx"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["shipment_number"], name="shipping_sh_shipmen_33cb73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["shipped_at"], name="shipping_sh_shipped_0d4cdb_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentitem",
            constraint=models.UniqueConstraint(
                fields=("shipment", "wr"), name="uniq_shipment_wr"
            ),
        ),
    ]
