# Generated by Django 6.0.2 on 2026-03-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_backfill_company_data"),
        ("shipping", "0002_shipment_company_shipmentitem_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipments",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="shipmentitem",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_items",
                to="company.company",
            ),
        ),
    ]
