# Generated by Django 6.0.2 on 2026-02-20 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("receiving", "0002_repackoperation_repacklink_and_more"),
        ("warehouse", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("RECEIVE", "Receive"),
                            ("PUTAWAY", "Putaway"),
                            ("MOVE", "Move"),
                            ("REPACK_CONSUME", "Repack Consume"),
                            ("REPACK_PRODUCE", "Repack Produce"),
                            ("SHIP", "Ship"),
                            ("ADJUST", "Adjust"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reference_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "performed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to="clients.client",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryTransactionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty", models.PositiveIntegerField(default=1)),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="txn_lines_from",
                        to="warehouse.storagelocation",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="txn_lines_to",
                        to="warehouse.storagelocation",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.inventorytransaction",
                    ),
                ),
                (
                    "wr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_transaction_lines",
                        to="receiving.warehousereceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("on_hand_qty", models.PositiveIntegerField(default=1)),
                ("reserved_qty", models.PositiveIntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_balances",
                        to="clients.client",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_balances",
                        to="warehouse.storagelocation",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_balances",
                        to="warehouse.warehouse",
                    ),
                ),
                (
                    "wr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_balances",
                        to="receiving.warehousereceipt",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["client"], name="inventory_i_client__abefff_idx"
                    ),
                    models.Index(
                        fields=["warehouse", "location"],
                        name="inventory_i_warehou_6b2546_idx",
                    ),
                    models.Index(fields=["wr"], name="inventory_i_wr_id_2392fb_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("location", "wr"), name="uniq_location_wr_balance"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["client", "performed_at"], name="inventory_i_client__4850c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransaction",
            index=models.Index(
                fields=["txn_type"], name="inventory_i_txn_typ_29bf1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransactionline",
            index=models.Index(
                fields=["transaction"], name="inventory_i_transac_30e30f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorytransactionline",
            index=models.Index(fields=["wr"], name="inventory_i_wr_id_c85f19_idx"),
        ),
    ]
