# Generated by Django 6.0.2 on 2026-03-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_associatecompany_office"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybalance",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_balances",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransaction",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_transactions",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="inventorytransactionline",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_transaction_lines",
                to="company.company",
            ),
        ),
    ]
