# Generated by Django 6.0.2 on 2026-03-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_backfill_company_data"),
        ("inventory", "0002_inventorybalance_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorybalance",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_balances",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransaction",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_transactions",
                to="company.company",
            ),
        ),
        migrations.AlterField(
            model_name="inventorytransactionline",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_transaction_lines",
                to="company.company",
            ),
        ),
    ]
