# Generated by Django 6.0.2 on 2026-03-05 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_client_company"),
        ("company", "0003_backfill_company_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="company.company",
            ),
        ),
    ]
