# Generated by Django 6.0.2 on 2026-03-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_alter_client_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="cellphone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[("person", "Person"), ("company", "Company")],
                default="person",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="home_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, unique=True
            ),
        ),
    ]
