# Generated by Django 6.0.2 on 2026-04-10 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_notifications_configured_and_prefs'),
        ('company', '0006_company_subscription_queued_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='associate_company',
            field=models.ForeignKey(blank=True, help_text='Agency this client belongs to — used to attribute billing per agency.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='company.associatecompany'),
        ),
    ]
